Repository cn-uofbasel/ccn-lite, pull requests merged in 2018-02, with the labels that each got.

#190 fix minor compiler errors for arm cortex
  src/ccnl-core/src/ccnl-dump.c
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement, minor

#192 ndntlv: remove unaligned memory access for cortex m0
  src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
Labels: enhancement, minor

#194 Fix #193 prefix overruns in function ccnl_prefix_to_path_detailed [CVE-2018-6948]
  src/ccnl-core/include/ccnl-prefix.h
  src/ccnl-core/src/ccnl-prefix.c
  src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
Labels: bug, vulnerability

#202 ccn-lite-ctrl: fix parsing of UDP string
  src/ccnl-utils/ccn-lite-ctrl.c
Labels: bug

#203 ccn-lite-riot: MTU target too big
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug

#204 riot: provide multi-interface support
  src/ccnl-core/include/ccnl-defs.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement
