Repository cn-uofbasel/ccn-lite, pull requests merged in 2018-11, with the labels that each got.

#320 addresses dead assignments in ccn-lite-mkI/introduces error checks to ccn-lite-ctrl
  src/ccnl-utils/src/ccn-lite-ctrl.c
  src/ccnl-utils/src/ccn-lite-mkI.c
Labels: minor, regression

#321 replaces calls to atoi with strtol
  src/ccnl-relay/ccn-lite-relay.c
  src/ccnl-utils/src/ccn-lite-ctrl.c
  src/ccnl-utils/src/ccn-lite-deF.c
  src/ccnl-utils/src/ccn-lite-fetch.c
  src/ccnl-utils/src/ccn-lite-mkC.c
  src/ccnl-utils/src/ccn-lite-mkF.c
  src/ccnl-utils/src/ccn-lite-mkI.c
  src/ccnl-utils/src/ccn-lite-peek.c
  src/ccnl-utils/src/ccn-lite-peekcomputation.c
  src/ccnl-utils/src/ccn-lite-pktdump.c
  src/ccnl-utils/src/ccn-lite-produce.c
  src/ccnl-utils/src/ccn-lite-rpc.c
  src/ccnl-utils/src/ccn-lite-simplenfn.c
  src/ccnl-utils/src/ccn-lite-valid.c
  src/ccnl-utils/src/ccnl-socket.c
Labels: minor

#323 replaced calls to atof with strtof
  src/ccnl-utils/src/ccn-lite-fetch.c
  src/ccnl-utils/src/ccn-lite-peek.c
  src/ccnl-utils/src/ccn-lite-peekcomputation.c
  src/ccnl-utils/src/ccn-lite-rpc.c
  src/ccnl-utils/src/ccn-lite-simplenfn.c
Labels: minor

#328 ccnl-prefix: fix behavior of ccnl_i_prefixof_c
  src/ccnl-core/src/ccnl-prefix.c
Labels: bug

#332 changes type of length in struct ccnl_buf_s
  src/ccnl-core/include/ccnl-buf.h
  src/ccnl-core/src/ccnl-buf.c
  src/ccnl-core/src/ccnl-dump.c
  src/ccnl-core/src/ccnl-relay.c
Labels: minor
