Repository cn-uofbasel/ccn-lite, pull requests merged in 2018-05, with the labels that each got.

#237 provides templates for PRs and issues
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, minor

#235 created a short version of development procedures
  CONTRIBUTING.md
Labels: enhancement, minor

#246 cmake: don't build unused TLV fomats for RIOT
  src/CMakeLists.txt
  src/ccnl-pkt/src/ccnl-pkt-builder.c
Labels: enhancement, minor

#248 ccnl-riot: new line for debugmsg
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement, minor

#247 ccnl-riot: make thread prio configurable
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement, minor

#249 ccnl-prefix.c: (void) to soothe the compiler about unused params
  src/ccnl-core/src/ccnl-prefix.c
Labels: enhancement, minor

#254 ccnl-riot: add to CS in ccnl thread context
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement

#251 ccnl-fwd: do not set *pkt = NULL for local_producer
  src/ccnl-fwd/src/ccnl-fwd.c
Labels: bug, enhancement

#252 gcc: suppress empty translation unit errors
  src/ccnl-fwd/src/ccnl-localrpc.c
  src/ccnl-pkt/src/ccnl-pkt-ccnb.c
  src/ccnl-pkt/src/ccnl-pkt-ccntlv.c
  src/ccnl-pkt/src/ccnl-pkt-localrpc.c
Labels: enhancement, minor

#257 ccnl-callbacks: add support for on-data events
  src/ccnl-core/include/ccnl-callbacks.h
  src/ccnl-core/src/ccnl-callbacks.c
  src/ccnl-fwd/src/ccnl-fwd.c
Labels: enhancement

#253 ccnl-riot: send interest in ccnl thread context
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement

#255 ccnl-riot: remove from CS in ccnl thread context
  src/ccnl-core/include/ccnl-relay.h
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement

#250 ccnl-riot: exit early on error for ccnl_send_interest()
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement, minor

#256 ccnl-riot: lookup CS in ccnl thread context
  src/ccnl-core/include/ccnl-relay.h
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement

#258 ccnl-riot: ccnl_event_loop_pid renaming
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement, minor

#262 ccnl/riot: move reset of retransmission timer
  src/ccnl-core/src/ccnl-interest.c
  src/ccnl-core/src/ccnl-relay.c
Labels: bug, riot

#261 ccnl-riot: face evtimer
  src/ccnl-core/include/ccnl-face.h
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/include/ccn-lite-riot.h
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: enhancement, minor, riot

#263 ccnl/riot: cache timeout based on evtimer
  src/ccnl-core/include/ccnl-content.h
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/include/ccn-lite-riot.h
Labels: enhancement, riot

#265 ccnl/riot: make debug message unique
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: minor, riot
