Repository cn-uofbasel/ccn-lite, pull requests merged in 2018-06, with the labels that each got.

#266 fixes ccnl_content_add2cache prefix comparison
  src/ccnl-core/src/ccnl-relay.c
Labels: minor

#267 make ccnl-content.h part of doxygen-based API documentation
  src/ccnl-core/include/ccnl-content.h
Labels: minor

#268 ccnl-fwd: check content duplicates only by name, not all packet bytes
  src/ccnl-fwd/src/ccnl-fwd.c
Labels: enhancement, minor

#269 ccnl-relay: add missing evtimers for interest retrans/timeout
  src/ccnl-core/src/ccnl-relay.c
Labels: bug, enhancement, minor

#270 removes source file includes in ccnl-utils
  src/ccnl-utils/CMakeLists.txt
  src/ccnl-utils/include/base64.h
  src/ccnl-utils/include/ccnl-common.h
  src/ccnl-utils/include/ccnl-crypto.h
  src/ccnl-utils/include/ccnl-ext-hmac.h
  src/ccnl-utils/include/ccnl-socket.h
  src/ccnl-utils/include/lib-sha256.h
  src/ccnl-utils/src/base64.c
  src/ccnl-utils/src/ccn-lite-ccnb2xml.c
  src/ccnl-utils/src/ccn-lite-cryptoserver.c
  src/ccnl-utils/src/ccn-lite-ctrl.c
  src/ccnl-utils/src/ccn-lite-deF.c
  src/ccnl-utils/src/ccn-lite-fetch.c
  src/ccnl-utils/src/ccn-lite-mkC.c
  src/ccnl-utils/src/ccn-lite-mkF.c
  src/ccnl-utils/src/ccn-lite-mkI.c
  src/ccnl-utils/src/ccn-lite-ndnstream.py
  src/ccnl-utils/src/ccn-lite-peek.c
  src/ccnl-utils/src/ccn-lite-peekcomputation.c
  src/ccnl-utils/src/ccn-lite-pktdump.c
  src/ccnl-utils/src/ccn-lite-produce.c
  src/ccnl-utils/src/ccn-lite-rpc.c
  src/ccnl-utils/src/ccn-lite-simplenfn.c
  src/ccnl-utils/src/ccn-lite-valid.c
  src/ccnl-utils/src/ccnl-common.c
  src/ccnl-utils/src/ccnl-crypto.c
  src/ccnl-utils/src/ccnl-ext-hmac.c
  src/ccnl-utils/src/ccnl-socket.c
  src/ccnl-utils/src/lib-sha256.c
Labels: minor, requires squashing

#275 replaces int parameters in calloc/malloc/realloc calls with size_t
  src/ccnl-core/include/ccnl-malloc.h
  src/ccnl-core/src/ccnl-logging.c
  src/ccnl-core/src/ccnl-malloc.c
Labels: minor

#278 ccnl-riot: fix missing include for ccnl-overflow.h
  src/ccnl-riot/CMakeLists.txt
Labels: bug, minor, riot
