Repository cn-uofbasel/ccn-lite, pull requests merged in 2018-03, with the labels that each got.

#197 Fix #195 [CVE-2018-6953]
  src/CMakeLists.txt
  src/ccnl-core/src/ccnl-prefix.c
  src/ccnl-pkt/include/ccnl-pkt-ccntlv.h
  src/ccnl-pkt/include/ccnl-pkt-cistlv.h
  src/ccnl-pkt/include/ccnl-pkt-iottlv.h
  src/ccnl-pkt/include/ccnl-pkt-ndntlv.h
  src/ccnl-pkt/src/ccnl-pkt-ccntlv.c
  src/ccnl-pkt/src/ccnl-pkt-cistlv.c
  src/ccnl-pkt/src/ccnl-pkt-iottlv.c
  src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
  src/ccnl-unix/src/ccnl-unix.c
Labels: bug, vulnerability

#206 ccnl-relay: check if face ifndx matches given ifndx
  src/ccnl-core/src/ccnl-relay.c
Labels: bug, question

#209 ccnl-riot: initialize fields for default options
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, minor

#215 some memsantization
  src/ccnl-unix/src/ccnl-unix.c
Labels: bug
