Repository cn-uofbasel/ccn-lite, pull requests merged in 2019-06, with the labels that each got.

#353 type fixes for cross-compiling (e.g. with RIOT)
  src/ccnl-core/include/ccnl-prefix.h
  src/ccnl-core/src/ccnl-content.c
  src/ccnl-core/src/ccnl-dump.c
  src/ccnl-core/src/ccnl-prefix.c
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/src/ccn-lite-riot.c
Labels: bug, enhancement, minor

#355 make CCNL_DEFAULT_MAX_PIT_ENTRIES configurable
  src/ccnl-core/include/ccnl-defs.h
Labels: enhancement, riot

#354 ccnl-interest: check for max pit entries and free if full
  src/ccnl-core/src/ccnl-interest.c
  src/ccnl-core/src/ccnl-relay.c
Labels: bug, minor

#356 ccnl-riot: add a RIOT cleanup functions for Interest structures
  src/ccnl-core/src/ccnl-relay.c
  src/ccnl-riot/include/ccn-lite-riot.h
Labels: enhancement, minor, riot

#358 ccnl-pkt: use random_uint32() instead of rand() for RIOT
  src/ccnl-pkt/src/ccnl-pkt-builder.c
Labels: bug, enhancement, minor

#359 ccn-lite-riot: remove message from queue on remove interest
  src/ccnl-riot/include/ccn-lite-riot.h
Labels: bug, riot

#360 ccn-lite-riot: add include for irq.h
  src/ccnl-riot/include/ccn-lite-riot.h
Labels: riot

#361 ndn: fix nonce parsing when forwarding
  src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
Labels: bug, enhancement
