Repository cn-uofbasel/ccn-lite, pull requests merged in 2019-02, with the labels that each got.

#343 fixes parameter of sizeof in {test_prefix,ccn-lite-rpc}.c
  src/ccnl-utils/src/ccn-lite-rpc.c
  test/ccnl-core/test_prefix.c
Labels: minor

#347 ndntlv: remove superfluous write()
  src/ccnl-pkt/src/ccnl-pkt-ndntlv.c
Labels: enhancement, minor

#348 CMake: make PACKETFORMATS configurable and properly define CCNL_RIOT
  src/CMakeLists.txt
  src/ccnl-pkt/CMakeLists.txt
Labels: enhancement, minor

#349 interest: fix timeout calculation for suite != NDN-TLV
  src/ccnl-core/include/ccnl-pkt-util.h
  src/ccnl-core/src/ccnl-interest.c
  src/ccnl-core/src/ccnl-pkt-util.c
Labels: bug, enhancement

#350 removes ccn-lite-simplenfn.c from ccnl-utils
  src/ccnl-utils/src/ccn-lite-simplenfn.c
Labels: minor, regression

#351 ccnl-pkt-util: header cleanup
  src/ccnl-core/src/ccnl-pkt-util.c
Labels: enhancement, minor
